[workspace]
members = [
    "compiler/nagi"
, "compiler/nagi_checker", "compiler/nagi_command_option", "compiler/nagi_extender", "compiler/nagi_ir", "compiler/nagi_macros", "compiler/nagi_syntax_tree"]
