[package]
name = "nagi_cst"
version = "0.1.0"
edition = "2021"

[dependencies]
nagi_lexer = { version = "0.1.0", path = "../nagi_lexer" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.132"
