[package]
name = "nagi_extender"
version = "0.1.0"
edition = "2021"

[dependencies]
nagi_syntax_tree = { version = "0.1.0", path = "../nagi_syntax_tree" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.132"